//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTTTSMPCOWNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessService
    {
        public int FileId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public int CouncilId { get; set; }
    
        public virtual Council Council { get; set; }
    }
}
