//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTTTSMPCOWNZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Linq;

    public partial class ContactLeadership
    {
        public int ContactLeadershipId { get; set; }

        //To change label title value  
        [Required]
        [DisplayName("Member Name")]
        public string Name { get; set; }

        //To change label title value  
        [Required]
        [DisplayName("Telephone / Mobile Number")]
        public Nullable<int> PhoneNumber { get; set; }

        //To change label title value  
        [Required]
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public int CouncilId { get; set; }

        public virtual Council Council { get; set; }
    }
}
