//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTTTSMPCOWNZ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EOTTTSMPCOWNZEntities : DbContext
    {
        public EOTTTSMPCOWNZEntities()
            : base("name=EOTTTSMPCOWNZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessService> AccessServices { get; set; }
        public virtual DbSet<AGMMeetingMinutesFinancialReport> AGMMeetingMinutesFinancialReports { get; set; }
        public virtual DbSet<ContactLeadership> ContactLeaderships { get; set; }
        public virtual DbSet<Council> Councils { get; set; }
        public virtual DbSet<CouncilForum> CouncilForums { get; set; }
        public virtual DbSet<Events_CalendarOfService_Hours> Events_CalendarOfService_Hours { get; set; }
        public virtual DbSet<FacilitiesForum> FacilitiesForums { get; set; }
        public virtual DbSet<Fundraising> Fundraisings { get; set; }
        public virtual DbSet<FundraisingForum> FundraisingForums { get; set; }
        public virtual DbSet<Sundayschool> Sundayschools { get; set; }
        public virtual DbSet<SundayschoolForum> SundayschoolForums { get; set; }
    }
}
