//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTTTSMPCOWNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fundraising
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fundraising()
        {
            this.FundraisingForums = new HashSet<FundraisingForum>();
        }
    
        public int FundraisingId { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string FundTitle { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CouncilId { get; set; }
    
        public virtual Council Council { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundraisingForum> FundraisingForums { get; set; }
    }
}
