//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTTTSMPCOWNZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Parishioner
    {
        public int ParshionersId { get; set; }
        //To change label title value  
        //[Required]
        [DisplayName("First Middle Name")]
        //[StringLength(30, ErrorMessage = "Your First AND Middle Name can contain only 30 characters")]
        public string FirstMidName { get; set; }


        //To change label title value  
        //[Required]
        [DisplayName("Last Name")]
        //[StringLength(20, ErrorMessage = "Your Last Name can contain only 20 characters")]
        public string LastName { get; set; }



        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Enrollment Date")]
        public Nullable<System.DateTime> EnrollmentDate { get; set; }


        [Display(Name = "Birth Date")]
        [Required(ErrorMessage = "Birth Date is required.")]
        //[RegularExpression(@"(((0|1)[0-9]|2[0-9]|3[0-1])\/(0[1-9]|1[0-2])\/((19|20)\d\d))$", ErrorMessage = "Invalid date format.")]
        public Nullable<System.DateTime> Birthday { get; set; }

        //[Required(ErrorMessage = "gender Required")]
        public string Gender { get; set; }


        //To change label title value  
        [Required]
        [DisplayName("Telephone / Mobile Number")]
        [Phone]
        public Nullable<int> PhoneNumber { get; set; }



        //To change label title value  
        //[Required]
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
